### ISSUE TITLE
A question about the dangerous cell types

### ISSUE THREAD

**Issue by XUEbaogai0101** [Danko-Lab/TED#25] opened 2022-06-07 13:38 UTC
Hi!
Thank you very much for generating such convenient, useful, great and open tools to combine the scRNA and bulk-seq.
When I used my data to run, I had met a question the same as you mentioned in the FAQ.There are some cells which are highly similar transcription profiles to the tumor cells in my data, especially those representing the tumor cell origins. When I finished the work, I found these cells had a lower proportion compared with the reference, which are almost zero, while the tumor cells were overestimated. I don't want to select the signature genes, because I want a real and completed gene expression. I saw you mentioned about the leave-one-out test, but I don't know how to realize... 
Would you teach me about the leave-one-out test? I will appreciate it a lot.
Best!
XUE

**Comment by tinyi** [comment] 2022-06-08 15:42
Hi Xue,

Thank you for your interest in our work. Can I ask whether your bulk data
is from the matched sample as scRNA, or are they from different patients?
It would be great if you can give me a sense of the extent of difference
between the reference and bulk.

Best,

Tinyi

**Comment by XUEbaogai0101** [comment] 2022-06-08 15:48
Hi!
I used TED to intergrate TCGA_LAML data based on the single cell data of GSE116256. As in the blood diseases, the blast have a high correlation with the tumor cells, I analysed them and found that the correlation between the proportion of tumor in ref and BMblast in TCGA clinical information was only -0.02.Also, the proportion of monocytes presumed in TCGA was lower than ref obviously, as well as T cells and some types. Combined with my own blood disease data,what I mentioned above, do they indicate that TED is not performing well in blood disease, or am I using it incorrectly? Do you have any suggestions?
The filtered data of GSE116256 and others data used in my analysis are available at :https://github.com/XUEbaogai0101/bay.
And the code I run was as followed.
```
ref.dat.filtered <- cleanup.genes(ref.dat= ref.dat,  
                                  species="hs",  
                                  gene.type=c("RB","chrM","chrX","chrY"), 
                                  input.type="scRNA",  
                                  exp.cells=5)
tcga.ted <- run.Ted(ref.dat = ref.dat.filtered,
                    X = X,
                    tum.key = 'tumor',
                    cell.type.labels = anno$CellType,
                    cell.subtype.labels = anno$Cellsubtype,
                    input.type = 'scRNA',
                    n.cores = 20)
colnames(blast) <- c('patients','BMblast')
bls_tpm <- ''
bay_tpm <- ''
for (i in 1:length(blast$patients)) {
  if (length(grep(blast$patients[i],rownames(celltype_por))) != 0) {
    tpm1 <- blast$patients[i]
    bls_tpm <- rbind(bls_tpm,tpm1)
    tpm2 <- grep(blast$patients[i],rownames(celltype_por),value = T)
    bay_tpm <- rbind(bay_tpm,tpm2)
  }
}
bls_tpm <- bls_tpm[-1,]
bay_tpm <- bay_tpm[-1,]
clinic_blast <- blast[which(blast$patients %in% tpm),]
tcga_celltype <- as.data.frame(tcga.ted$res$first.gibbs.res$theta.merged)
tcga_pear <- tcga_celltype[bay_tpm,]$tumor
clinic_blast$tcga <- round(tcga_pear*100)
cor(clinic_blast$BMblast,clinic_blast$tcga,method="pearson",use="complete.obs")
plot(clinic_blast$tcga, clinic_blast$blasts, main = "Main title",
     xlab = "bay axis title", ylab = "clinic axis title",
     pch = 19, frame = T)
```
I wish I have clear my question.Thank you very much!
Best!
XUE

**Comment by XUEbaogai0101** [comment] 2022-06-08 16:04
Hi Tinyi!
I finally got your answer T-T .Thank you very much!
About the bulk data, I was downloading from the TCGA_LAML recently.  Because I have read a paper which also combined TCGA and scRNA used by CIBERSORTx, it seemed to have performed well. So I want to use my data or opened data to repeat similar outcomes.  I also uploaded their outcome on my github, which is named 'CIBERSORTx_Results_TCGA.csv' and also referred to GSE116256. In this csv, cellnames with '-like' were tumor cell. I am looking forward to using your method to complete a nice job. 
Best!
XUE

**Comment by XUEbaogai0101** [comment] 2022-06-08 19:12
I have tried subset the scRNA-seq reference on signature genes to analysis. Unfortunately, the outcome was similar to before.
​Mono, T and GMP were lower than expected and different with the outcome of CIBERSORTx tested in the paper mentioned above.
```
num   tumor   GMP  Mono  Prog   cDC   HSC ProMono earlyEry   CTL     T Plasma  ProB    NK     B lateEry   pDC
Min.    0.345 0.000 0.000 0.000 0.000 0.000       0    0.000 0.000 0.000  0.000 0.000 0.000 0.000   0.000 0.000
1st Qu. 0.690 0.000 0.000 0.000 0.000 0.000       0    0.000 0.000 0.000  0.000 0.000 0.000 0.000   0.000 0.038
Median  0.788 0.000 0.000 0.000 0.000 0.000       0    0.000 0.003 0.000  0.000 0.000 0.004 0.000   0.005 0.078
Mean    0.766 0.004 0.001 0.000 0.013 0.025       0    0.025 0.014 0.004  0.002 0.012 0.018 0.012   0.021 0.082
3rd Qu. 0.856 0.000 0.000 0.000 0.000 0.015       0    0.000 0.021 0.002  0.003 0.007 0.024 0.013   0.019 0.119
Max.    0.989 0.115 0.053 0.013 0.221 0.320       0    0.456 0.125 0.052  0.023 0.151 0.178 0.127   0.170 0.257
```

**Comment by tinyi** [comment] 2022-06-08 23:30
Hi Xue,

I just looked into your data a bit. It looks like the tumor fraction seems
to be systematically higher than cibersortx . There are a few reasons for
this.

The first possibility is that there are way more tumor cells than non-tumor
cells in your reference (16 to 264 times more). This may give you a less
sparse representation for tumor than the non-tumor cells, so that the reads
in bulk will be assigned to tumor for those genes with zero expression in
non-tumor cells. We also observe similar effects in T cells of GBM (see
Supplementary Fig. 1e of our BayesPrism paper). Under such circumstance,
although the absolute fraction will be underestimated for some cell types
with too few cells, the relative fractions are still accurate.

The other possibility is that the fraction inferred by BayesPrism
represents the fraction of reads (rather than the cell count) of each cell
type in each bulk. As a result, cells with low total transcription level
will have lower fraction of reads. Tumor may have higher amount of total
transcription than other cells, such as T cell. This may contribute to the
seemingly over-estimated tumor fractions.

I found that the paper you gave me contains some samples with matched bulk
RNA-seq (https://www.nature.com/articles/s41591-022-01819-x/figures/8),
perhaps they can be used for benchmarking to get an idea of how
BayesPrism performs in your particular system.

Let me know if there is any other questions.

Best,

Tinyi

**Comment by XUEbaogai0101** [comment] 2022-06-09 02:45
Thanks!

**Comment by XUEbaogai0101** [comment] 2022-06-09 15:31
Hi Tinyi!
​Eventually, I discovered the appropriate signature gene to differentiate my cell types, and the updated cell types matrix as followed satisfied my expectation, but I could not see the updated distribution of cell states, which is also essential for me. Could you give me some suggestions to explore the update methods about the cell states matrix? Because the first outcome of cell states as followed wasn't what I anticipated. Another question is that, if I want to use the updated cell fraction, should the gene expression be updated? If it's necessary, how can I realize?
```
updated cell types matrix

num     tumor  Mono   cDC   CTL     T Plasma    NK     B
Min.    0.000 0.000 0.000 0.000 0.000  0.000 0.000 0.000
1st Qu. 0.491 0.000 0.000 0.000 0.000  0.000 0.000 0.000
Median  0.665 0.000 0.004 0.025 0.000  0.002 0.000 0.008
Mean    0.628 0.100 0.092 0.044 0.028  0.010 0.033 0.064
3rd Qu. 0.851 0.137 0.139 0.075 0.018  0.013 0.024 0.105
Max.    0.985 0.800 0.664 0.236 0.515  0.115 0.432 0.500
```
```
fist outcome of cell states

num       GMP-like Prog-like ProMono-like HSC-like cDC-like Mono-like  Mono   cDC   CTL     T Plasma    NK     B
Min.       0.000     0.000       0.000    0.000    0.000     0.000    0.000 0.000 0.000 0.000  0.000 0.000 0.000
1st Qu.    0.012     0.000       0.000    0.172    0.000     0.000    0.000 0.000 0.000 0.000  0.000 0.000 0.001
Median     0.094     0.000       0.000    0.341    0.000     0.020    0.000 0.058 0.010 0.000  0.001 0.016 0.017
Mean       0.178     0.020       0.026    0.360    0.042     0.107    0.035 0.102 0.024 0.002  0.006 0.049 0.046
3rd Qu.    0.301     0.001       0.000    0.528    0.009     0.133    0.029 0.163 0.039 0.000  0.007 0.063 0.073
Max.       0.855     0.611       0.471    0.971    0.556     0.774    0.327 0.583 0.138 0.078  0.098 0.409 0.329
```
Thank you very much!
Best!
XUE

**Comment by tinyi** [comment] 2022-06-10 23:16
Hi Xue,

If you have already run cibersortx, one option for signature genes is to
use the output from cibersortx. That being said, you can certainly define
your signature genes for each cell type by performing differential
expression.

By design, cell state is to be marginalized after the first gibbs sampling,
and hence will not be updated. Your cell states are for malignant cells,
which will be summarized as a sample-specific profile in the updated
reference profile.

We do not report updated gene expression for updated gibbs sampling, as it
does not necessarily improve over the expression estimated by first gibbs
sampling when benchmarking our dataset.

Best,

Tinyi

**Comment by XUEbaogai0101** [comment] 2022-06-10 23:38
Hi Tinyi! Thank you very much! You help me a lot! I didn't run the cibersortx, I found the signature genes by using the commanded way you had mentioned in the FAQ. It's a pity that the proportion of T cell in the first gibbs sampling didn't satisfy my expectations. But I have seen the hope from 'updated cell types matrix', I would still try to improve my outcome in different ways. Thank you very much!

**Closed as completed** 2022-06-11 12:15 UTC
